### ISSUE TITLE
Windows 下怎么用 ?

### ISSUE THREAD

**Issue by ghost** [maijz128/github-update-checker#1]

**Comment by maijz128** [comment]
你的意思是这个代码有什么用？还是这个代码用不了？

**Comment by sgrjyb** [comment]
代码 然后呢 ?

**Comment by maijz128** [comment]
？？？
这个仓库的代码，本来我打算用于插件/MOD管理器的

**Comment by ghost** [comment]
这个代码 我该怎么用才能检测仓库更新 ?  因为它不是程序 我不是程序员

**Comment by maijz128** [comment]
如果你只打算要一个只有检测仓库版本更新功能的程序，我可以编译给你。
而这个程序，你大概需要怎么样的？

**Comment by ghost** [comment]
可以定时更新吧  邮件通知能做到吗 ?

**Comment by maijz128** [comment]
你需要功能的是否是：指定仓库有新版本的时候能通知你。

如果是不限方式的话，可以用RSS订阅。比如订阅下面的链接：
https://github.com/maijz128/github-update-checker/releases.atom

如果只限于邮件通知的话，我不清楚GitHub官方或其他网站支持这样的的功能。

如果一定要这样功能， 程序上大概可以做到。大概思路是程序隔一段时间通过访问网络检查是否有更新，有更新的话就发邮件给你。

**Comment by sgrjyb** [comment]
你需要功能的是否是：指定仓库有新版本的时候能通知你。 是

**Comment by maijz128** [comment]
我个人建议是用RSS订阅。

**Comment by ghost** [comment]
RSS 没有下载链接

**Comment by maijz128** [comment]
我不是很清楚你需这功能的使用环境。
PC? 手机?

**Comment by sgrjyb** [comment]
算了 你用rss 能不能分享一下 RSS源 ?

**Comment by maijz128** [comment]
订阅指定仓库的RSS源方法：
https://github.com/作者名/项目名/releases.atom

比如你star的项目：
https://github.com/EvilCult/moviecatcher/releases.atom
